const macos = navigator.platform.indexOf('Mac') > -1;
const modifier = macos ? '\u2318' : 'Ctrl';
document.getElementById('modifier').innerText = modifier;

document.addEventListener('keydown', function(event) {
    if ((macos ? event.metaKey : event.ctrlKey) && event.key === 'b') {
        event.preventDefault();
        boop();
    }
});

const dialog = document.querySelector('#selector');
const input = document.querySelector('#selector > input');
input.addEventListener('keydown', function(event) {
    if (event.key === 'Enter') {
        action(input.value);
        input.value = '';
        dialog.close();
    }
});

function boop() {
    document.querySelectorAll('header > div').forEach(x => x.hidden = !x.hidden);
    document.querySelector('#selector').showModal();
}

function action(a) {
    document.querySelectorAll('header > div').forEach(x => x.hidden = !x.hidden);
    if(!a) return;

}

const index = [
    {
      api: 1,
      name: "ASCII To Hex",
      description: "Converts ASCII characters to hexadecimal codes.",
      author: "aWZHY0yQH81uOYvH",
      icon: "metamorphose",
      tags: "ascii,hex,convert",
    },
    {
      api: 1,
      name: "Add Slashes",
      description: "Escapes your text.",
      author: "Ivan",
      icon: "quote",
      tags: "add,slashes,escape",
    },
    {
      api: 1,
      name: "Android Strings to iOS Localizables",
      description: "Converts Android Strings to iOS localizables.",
      author: "Manuel Kunz (https://github.com/KunzManuel)",
      icon: "translation",
      tags: "string,android,ios",
    },
    {
      api: 1,
      name: "Base64 Decode",
      description: "Decodes your text from Base64",
      author: "See Source",
      icon: "metamorphose",
      tags: "base64,btoa,decode",
    },
    {
      api: 1,
      name: "Base64 Encode",
      description: "Encodes your text to Base64",
      author: "See Source",
      icon: "metamorphose",
      tags: "base64,atob,encode",
    },
    {
      api: 1,
      name: "Binary to Decimal",
      description: "Converts binary values to decimal.",
      author: "Maurice",
      icon: "metamorphose",
      tags: "decimal,binary,dec,bin",
    },
    {
      api: 2,
      name: "CSV to JSON",
      description: "Converts comma-separated tables to JSON.",
      author: "Ivan",
      icon: "table",
      tags: "table,convert",
      bias: -0.2,
    },
    {
      api: 1,
      name: "CSV to JSON (headerless)",
      description: "Converts comma-separated, headerless tables to JSON.",
      author: "Flare576",
      icon: "table",
      tags: "table,convert",
      bias: -0.2,
    },
    {
      api: 1,
      name: "Calculate Size (Bytes)",
      description: "Calculates size of text in Bytes",
      author: "zzz",
      icon: "counter",
      tags: "calc,size,bytes,storage",
    },
    {
      api: 1,
      name: "Camel Case",
      description: "convertsYourTextToCamelCase",
      author: "Ivan",
      icon: "camel",
      tags: "camel,case,function,lodash",
    },
    {
      api: 1,
      name: "Collapse lines",
      description: "Removes all linebreaks from your text",
      author: "Dennis",
      icon: "collapse",
      tags: "strip,remove,collapse,join",
    },
    {
      api: 1,
      name: "Count Characters",
      description: "Get the length of your text",
      author: "Ivan",
      icon: "counter",
      tags: "count,length,size,character",
    },
    {
      api: 1,
      name: "Count Lines",
      description: "Get the line count of your text",
      author: "andipaetzold",
      icon: "counter",
      tags: "count,length,size,line",
    },
    {
      api: 1,
      name: "Count Words",
      description: "Get the word count of your text",
      author: "Daniel Stone",
      icon: "counter",
      tags: "count,length,size,words",
    },
    {
      api: 1,
      name: "Create Project Glossary Markdown File",
      description: "Type 'help' and run this script for instructions.",
      author: "Terry L. Lewis",
      icon: "colosseum",
      tags: "markdown,glossary",
      bias: 0.0,
    },
    ///
    /// Generates a Markdown Glossary file for the project specified in the input parameters.
    /// Run the script with no input text to create the input JSON required by the glossary generator.
    /// Fill in the required values, and re-run the Boop Script to generate the glossary.
    ///
  
    {
      api: 1,
      name: "Digi to ASCII",
      description: "Digi to ASCII",
      author: "Joseph Ng Rong En",
      icon: "dice",
      tags: "ascii,digi",
    },
    {
      api: 1,
      name: "Date to Timestamp",
      description: "Converts dates to Unix timestamp.",
      author: "Noah Halford",
      icon: "watch",
      tags: "date,time,calendar,unix,timestamp",
    },
    {
      api: 1,
      name: "Date to UTC",
      description: "Converts dates and timestamps to UTC dates",
      author: "Ivan",
      icon: "watch",
      tags: "date,time,calendar,unix,timestamp",
    },
    {
      api: 1,
      name: "Deburr",
      description: "Converts your text to basic latin characters.",
      author: "Ivan",
      icon: "colosseum",
      tags: "burr,special,characters,function,lodash",
    },
    {
      api: 1,
      name: "Decimal to Binary",
      description: "Converts decimal values to binary.",
      author: "Maurice",
      icon: "metamorphose",
      tags: "decimal,binary,dec,bin",
    },
    {
      api: 1,
      name: "Decimal to Hex",
      description: "Converts decimal values to hexadecimal.",
      author: "Maurice",
      icon: "metamorphose",
      tags: "decimal,hexadecimal,dec,hex",
    },
    {
      api: 1,
      name: "Downcase",
      description: "Converts your text to lowercase.",
      author: "Dan2552",
      icon: "type",
      tags: "downcase,lowercase",
    },
    {
      api: 1,
      name: "Eval Javascript",
      description: "Runs your text as Javascript Code.",
      author: "Sebastiaan Besselsen",
      icon: "command",
      tags: "js,script,run",
    },
    {
      api: 1,
      name: "Fish PATH Hex Converter",
      description: "Escapes terminal characters.",
      author: "Paul Seelman",
      icon: "broom",
      tags: "fish_user_paths, fish, hex, ascii, path, var",
    },
    {
      api: 1,
      name: "Format CSS",
      description: "Cleans and format CSS stylesheets.",
      author: "Ivan",
      icon: "broom",
      tags: "css,prettify,clean,indent",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Format JSON",
      description: "Cleans and format JSON documents.",
      author: "Ivan",
      icon: "broom",
      tags: "json,prettify,clean,indent",
    },
    {
      api: 1,
      name: "Format SQL",
      description: "Cleans and format SQL queries.",
      author: "Ivan",
      icon: "broom",
      tags: "mysql,sql,prettify,clean,indent",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Format XML",
      description: "Cleans and format XML/HTML documents.",
      author: "Ivan",
      icon: "broom",
      tags: "html,prettify,clean,indent",
      bias: -0.1,
    },
    {
      api: 1,
      name: "From string from unicode scaped",
      description:
        "Returns a readable string from the unicode scaped string (js format)",
      author: "luisfontes19",
      icon: "broom",
      tags: "string,normalize,convert,readable,unicode",
    },
    {
      api: 1,
      name: "HTML Decode",
      description: "Decodes HTML entities in your text",
      author: "See Source",
      icon: "HTML",
      tags: "html,decode,web",
    },
    {
      api: 1,
      name: "HTML Encode",
      description: "Encodes HTML entities in your text",
      author: "See Source",
      icon: "HTML",
      tags: "html,encode,web",
    },
    {
      api: 1,
      name: "HTML Encode all characters",
      description: "HTML Encodes every character in your text",
      author: "Ivan",
      icon: "HTML",
      tags: "html,encode,web,email",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Hex To ASCII",
      description: "Converts hexadecimal values into ASCII characters",
      author: "aWZHY0yQH81uOYvH",
      icon: "metamorphose",
      tags: "hex,ascii,convert",
    },
    {
      api: 1,
      name: "Hex to Dec",
      description: "Converts hexadecimal to decimal.",
      author: "Maurice",
      icon: "metamorphose",
      tags: "decimal,hexadecimal,dec,hex",
    },
    {
      api: 1,
      name: "iOS Localizables to Android Strings",
      description: "Converts iOS Localizables to Android Strings",
      author: "Manuel Kunz (https://github.com/KunzManuel)",
      icon: "translation",
      tags: "string,android,ios",
    },
    {
      api: 1,
      name: "JSON to CSV",
      description: "Converts JSON to comma-separated tables.",
      author: "Ivan",
      icon: "table",
      tags: "table,convert",
      bias: -0.2,
    },
    // Inspired by https://stackoverflow.com/a/31536517/2053038
    // Note: it would be good to escape commas, and maybe not just get keys from the first object.
  
    {
      api: 1,
      name: "JSON to YAML",
      description: "Converts JSON to YAML.",
      author: "Ivan",
      icon: "metamorphose",
      tags: "markup,convert",
    },
    {
      api: 1,
      name: "JWT Decode",
      description: "Converts JWTs to JSON",
      author: "Nils Sonemann",
      icon: "identification",
      tags: "decode,jwt,token",
    },
    {
      api: 1,
      name: "Join Lines",
      description: "Joins all lines without any delimiter.",
      author: "riesentoaster",
      icon: "collapse",
      tags: "join",
    },
    {
      api: 1,
      name: "Join Lines With Comma",
      description: "Joins all lines with a comma.",
      author: "riesentoaster",
      icon: "collapse",
      tags: "join, comma",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Join Lines With Space",
      description: "Joins all lines with a space",
      author: "riesentoaster",
      icon: "collapse",
      tags: "join, space",
      bias: -0.1,
    },
    {
      api: 1,
      name: "JS Object to JSON",
      description: "Converts a javascript object to JSON format",
      author: "luisfontes19",
      icon: "HTML",
      tags: "json,js,object,convert",
      bias: -0.1,
    },
    {
      api: 1,
      name: "JSON to Query String",
      description: "Converts JSON to URL query string.",
      author: "Ota Mares <ota@mares.one>",
      icon: "website",
      tags: "url,query,params,json,convert,encode",
    },
    {
      api: 1,
      name: "Kebab Case",
      description: "converts-your-text-to-kebab-case.",
      author: "Ivan",
      icon: "kebab",
      tags: "kebab,case,function,lodash",
    },
    {
      api: 1,
      name: "Line compare",
      description: "Check if existing lines have all the same content",
      author: "Luis Fontes",
      icon: "type",
      tags: "string,match,text,compare,line",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Lorem Ipsum",
      description: "Generates Lorem Ipsum placeholder text.",
      author: "luisfontes19",
      icon: "type",
      tags: "generate,lorem,ipsum,text",
      bias: -0.1,
    },
    {
      api: 1,
      name: "MD5 Checksum",
      description: "Computes the checksum of your text (Hex encoded).",
      author: "Ivan",
      icon: "fingerprint",
      tags: "strip,slashes,remove",
    },
    {
      api: 1,
      name: "Markdown Quote",
      description: "Adds > to the start of every line of your text.",
      author: "Dan2552",
      icon: "term",
      tags: "quote,markdown",
    },
    {
      api: 1,
      name: "Minify CSS",
      description: "Cleans and minifies CSS stylesheets.",
      author: "Ivan",
      icon: "broom",
      tags: "css,minify,clean,indent",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Minify JSON",
      description: "Cleans and minifies JSON documents.",
      author: "riesentoaster",
      icon: "broom",
      tags: "html,minify,clean,indent",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Minify SQL",
      description: "Cleans and minifies SQL queries.",
      author: "Ivan",
      icon: "broom",
      tags: "mysql,sql,minify,clean,indent",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Minify XML",
      description: "Cleans and minifies XML/HTML documents.",
      author: "Ivan",
      icon: "broom",
      tags: "html,minify,clean,indent",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Natural Sort Lines",
      description: "Sort lines with smart handling of numbers.",
      author: "Sebastiaan Besselsen",
      icon: "sort-numbers",
      tags: "sort,natural,natsort",
    },
    {
      api: 1,
      name: "New Boop Script",
      description: "Returns a basic Boop script.",
      author: "tlewis",
      icon: "quote",
      tags: "boop,state,script,debug,new,create",
    },
    {
      api: 1,
      name: "PHP Unserialize",
      description: "Convert PHP serialized data to JSON",
      author: "Rob Bogie",
      icon: "elephant",
      tags: "php,serialize,unserialize,json",
    },
    {
      api: 1,
      name: "Query String to JSON",
      description: "Converts URL query string to JSON.",
      author: "Ota Mares <ota@mares.one>",
      icon: "website",
      tags: "url,query,params,json,convert,decode",
    },
    {
      api: 1,
      name: "Remove Duplicate Lines",
      description: "Ensures each line of your text is unique.",
      author: "andipaetzold",
      icon: "filtration",
      tags: "unique,duplicate",
    },
    {
      api: 1,
      name: "Remove Slashes",
      description: "Unescapes your text.",
      author: "Ivan",
      icon: "quote",
      tags: "strip,slashes,remove,unescape",
    },
    {
      api: 1,
      name: "Replace Smart Quotes",
      description: "Replace Smart Quotes with their simpler values.",
      author: "Thomas Bauer (https://github.com/tbauer428)",
      icon: "broom",
      tags: "smart,quotes,quotations,quotation,smart-quotes,smart-quotations",
    },
    {
      api: 1,
      name: "Reverse Lines",
      description: "Flips every line of your text.",
      author: "@Clarko",
      icon: "flip",
      tags: "reverse,order,invert,mirror,flip,upside,down",
    },
    {
      api: 1,
      name: "Reverse String",
      description: "!seod ti tahw sseuG",
      author: "See Source",
      icon: "flip",
      tags: "flip,mirror,invert",
    },
    {
      api: 1,
      name: "Rot13",
      description: "Applies the Rot13 cypher to your text.",
      author: "Paul Starr",
      icon: "roman",
      tags: "spoilers,encryption,plaintext",
    },
    {
      api: 1,
      name: "SHA1 Hash",
      description: "Computes the SHA1 hash of your text (Hex encoded)",
      icon: "fingerprint",
      tags: "strip,slashes,remove",
    },
    {
      api: 1,
      name: "SHA256 Hash",
      description: "Computes the SHA256 hash of your text (Hex encoded)",
      icon: "fingerprint",
      tags: "strip,slashes,remove",
    },
    {
      api: 1,
      name: "SHA512 Hash",
      description: "Computes the SHA512 hash of your text (Hex encoded)",
      icon: "fingerprint",
      tags: "strip,slashes,remove",
    },
    {
      api: 1,
      name: "Shuffle characters",
      description: "Shuffles characters randomly",
      author: "Christian Petersen",
      icon: "dice",
      tags: "shuffle,random,character,char",
    },
    {
      api: 1,
      name: "Shuffle Lines",
      description: "Randomize each line of your text.",
      author: "@Clarko",
      icon: "dice",
      tags: "shuffle,random",
    },
    {
      api: 1,
      name: "Snake Case",
      description: "converts_your_text_to_snake_case.",
      author: "Ivan",
      icon: "snake",
      tags: "snake,case,function,lodash",
    },
    {
      api: 1,
      name: "Sort lines",
      description: "Sort lines alphabetically.",
      author: "Sebastiaan Besselsen",
      icon: "sort-characters",
      tags: "sort,alphabet",
    },
    {
      api: 1,
      name: "Sort JSON",
      description: "Sort JSON",
      author: "MaDnh",
      icon: "sort-characters",
      tags: "json,sort",
    },
    {
      api: 1,
      name: "Sponge Case",
      description: "CoNvERtS yoUR Text To A HIghER fOrM Of CoMMUnICAtIOn",
      author: "Paul Seelman",
      icon: "pineapple",
      tags: "bob,sarcasm,no,this,is,patrick",
    },
    {
      api: 1,
      name: "Start Case",
      description: "Converts Your Text To Start Case.",
      author: "Ivan",
      icon: "type",
      tags: "start,case,function,lodash",
    },
    {
      api: 1,
      name: "Sum All",
      description: "Sums up a list of numbers.",
      author: "Annie Tran",
      icon: "abacus",
      tags: "sum,calculator,addition,add",
    },
    {
      api: 1,
      name: "Test Script",
      description: "Testing script",
      author: "Ivan",
      icon: "flask",
      tags: "test,test,one,two",
    },
    {
      api: 1,
      name: "Time to seconds",
      description: "Convert hh:mm:ss to seconds",
      author: "PeteChu",
      icon: "watch",
      tags: "transform,convert",
    },
    {
      api: 1,
      name: "Trim",
      description: "Trims leading and trailing whitespace.",
      author: "Joshua Nozzi",
      icon: "scissors",
      tags: "trim,whitespace,empty,space",
    },
    {
      api: 1,
      name: "Trim End",
      description: "Trims trailing whitespace.",
      author: "Joshua Nozzi",
      icon: "scissors",
      tags: "trim,end,right,trailing,whitespace,empty,space",
    },
    {
      api: 1,
      name: "Trim Start",
      description: "Trims leading whitespace.",
      author: "Joshua Nozzi",
      icon: "scissors",
      tags: "trim,start,left,leading,beginning,whitespace,empty,space",
    },
    {
      api: 1,
      name: "URL Decode",
      description: "Decodes URL entities in your text.",
      author: "Ivan",
      icon: "link",
      tags: "url,decode,convert",
    },
    {
      api: 1,
      name: "Defang",
      description: "Defangs dangerous URLs and other IOCs",
      author: "Ross",
      icon: "link",
      tags: "defang,url,ioc",
    },
    {
      api: 1,
      name: "URL Encode",
      description: "Encodes URL entities in your text.",
      author: "Ivan",
      icon: "link",
      tags: "url,encode,convert",
    },
    {
      api: 1,
      name: "URL Entities Decode",
      description: "URL Decodes all characters in your text.",
      author: "luisfontes19",
      icon: "percentage",
      tags: "url,decode,full",
      bias: -0.1,
    },
    {
      api: 1,
      name: "URL Entity Encode",
      description: "URL Encodes all characters in your text.",
      author: "luisfontes19",
      icon: "percentage",
      tags: "url,encode,full",
      bias: -0.1,
    },
    {
      api: 1,
      name: "Refang",
      description: "Removes defanging from dangerous URLs and other IOCs",
      author: "Ross",
      icon: "link",
      tags: "refang,url,ioc",
    },
    {
      api: 1,
      name: "Upcase",
      description: "Converts your text to uppercase.",
      author: "Dan2552",
      icon: "type",
      tags: "upcase,uppercase,capital,capitalize,capitalization",
    },
    {
      api: 1,
      name: "Wadsworth",
      description: "first 30% of your text.",
      author: "Ivan",
      icon: "scissors",
      tags: "snap",
    },
    {
      api: 1,
      name: "Well-Known Binary to Text",
      description: "Converts your hex encoded WKB (any endian) to WKB, wkb2wkt",
      author: "Mikael Brassman (Twitter: @spoike)",
      icon: "globe",
      tags: "wkb,convert,wkt,binary,hex,wkb2wkt",
    },
    {
      api: 1,
      name: "Well-Known Text to Binary",
      description:
        "Converts your WKT to little endian WKB (hex encoded), wkt2wkb",
      author: "Mikael Brassman (Twitter: @spoike)",
      icon: "globe",
      tags: "wkb,convert,wkt,binary,little endian,hex,wkt2wkb",
    },
    {
      api: 1,
      name: "YAML to JSON",
      description: "Converts YAML to JSON.",
      author: "Ivan",
      icon: "metamorphose",
      tags: "markup,convert",
    },
    {
      api: 1,
      name: "Contrasting Color",
      description:
        "Determine whether black or white contrasts better with the given color(s) (one per line).",
      author: "Sunny Walker",
      icon: "color-wheel",
      tags: "contrast,color,wcag",
    },
    {
      api: 1,
      name: "Convert to pretty markdown table",
      description:
        "Converts csv, tsv or markdown table into pretty markdown table format.",
      author: "xshoji",
      icon: "term",
      tags: "csv,tsv,md,markdown",
    },
    {
      api: 1,
      name: "Generate hashtag",
      description: "Generate hashtag from a word or sentence",
      author: "Armand Salle",
      icon: "metamorphose",
      tags: "hashtag,word",
    },
    {
      api: 1,
      name: "Hex to RGB",
      description: "Convert color in hexadecimal to RGB.",
      author: "Venkat",
      icon: "color-wheel",
      tags: "hex,color,rgb,convert",
    },
    {
      api: 1,
      name: "JS To PHP",
      description: "Convert JS Object or Array to PHP.",
      author: "jtolj",
      icon: "elephant",
      tags: "js,php,convert",
    },
    {
      api: 1,
      name: "List to HTML list",
      description: "Turns comma separated list to HTML Lists",
      author: "Christian Heilmann",
      icon: "table",
      tags: "HTML,Lists",
    },
    {
      api: 1,
      name: "RGB to Hex",
      description: "Convert color in RGB to hexadecimal",
      author: "luisfontes19",
      icon: "color-wheel",
      tags: "rgb,hex,convert,color",
    },
    {
      api: 1,
      name: "To Unicode Escaped String",
      description: "Converts a UTF8 string to unicode escape chars(js format)",
      author: "luisfontes19",
      icon: "broom",
      tags: "string,unicode,convert,escape",
    },
    {
      api: 1,
      name: "Toggle Camel and Hyphen",
      description: "Turns camelCase to camel-case and vice versa",
      author: "Christian Heilmann",
      icon: "table",
      tags: "camelcase,hyphencase,syntax,codestandards",
    },
    {
      api: 1,
      name: "TSV to JSON",
      description: "Converts TSV to JSON",
      author: "Quddus George",
      icon: "table",
      tags: "tab, tsv, json, table",
    },
  ];
  console.log(index);
  